
import React from 'react'
import { DiscoverButton, StatusCard, StatusWrapper, TitleWrapper, TrackContainer  } from './TrackRecord.style'
import { Typography } from '@mui/material'
import ArrowOutwardIcon from '@mui/icons-material/ArrowOutward';

const TrackRecord = () => {

  const statusData = [
    {total:"112+",
      title:"Web & Mobile Apps Delivered"
    },
    {total:"35+",
      title:"AI, Web3 & Enterprise Solutions Built"
    },
    {total:"740,000+",
      title:"DAUs managed"
    },
    {total:"$6.2M+",
      title:"Revenue generated by client products"
    }
  ]

  return (
    <TrackContainer >
    <TitleWrapper>
        <Typography variant='h1'>
            Proven Track Record
        </Typography>
        <Typography sx={{color:"#AAAAAA"}} variant='h5'>
            We&#39;re not just developers. We&#39;re your growth partners from concept to scale.
        </Typography>
        <DiscoverButton>
            Discover <ArrowOutwardIcon sx={{fontSize:"17px", marginLeft:"6px"}} />
        </DiscoverButton>
    </TitleWrapper>

     <StatusWrapper>
        {statusData.map((item, index) => {
          return(
            <StatusCard
              key={index}
              sx={{
                ...(index === 0 || index === 2) && {
                  backgroundImage: "url('/trackbg.gif')",
                  backgroundSize: "cover",
                  backgroundPosition: "center",
                },
                ...(index === 0 && {
                  borderTopLeftRadius: "12px",
                  borderBottomLeftRadius: "12px",
                }),
                ...(index === statusData.length - 1 && {
                  borderTopRightRadius: "12px",
                  borderBottomRightRadius: "12px",
                }),
              }}
            >
              <Typography sx={{fontSize:"85px", color: "white"}}>
                {item.total}
              </Typography>
              <Typography sx={{color:"#FFFFFF"}} variant='h5'>{item.title}</Typography>
            </StatusCard>
          )
        })}
      </StatusWrapper>
    </TrackContainer>
  )
}

export default TrackRecord ;
