"use client";

import React, { useRef } from "react";
import {
  DescriptionText,
  NumberText,
  StatusCard,
  StatusWrapper,
  TitleText,
  TitleWrapper,
  TrackContainer,
} from "./TrackRecord.style";

import { useGsapCounterAnimation } from "@/hooks/useGsapAnimation";
import PageContainer from "@/components/common/PageContainer";
import DiscoverButton from "@/components/ui/DiscoverButton";
import Link from "next/link";

const statusData = [
  { total: 112, suffix: "+", title: "Web & Mobile Apps Delivered" },
  { total: 35, suffix: "+", title: "AI, Web3 & Enterprise Solutions Built" },
  { total: 740000, suffix: "+", title: "DAUs managed" },
  { total: 6.2, prefix: "$", suffix: "M+", title: "Revenue generated by client products" },
];

const TrackRecord: React.FC = () => {
  const numberRefs = useRef<(HTMLDivElement | null)[]>([]);
  useGsapCounterAnimation(numberRefs, statusData);

  return (
    <TrackContainer>
      <PageContainer>
        <TitleWrapper>
          <TitleText variant="h1">Proven Track Record</TitleText>
          <DescriptionText variant="h5">
            We&apos;re not just developers. We&apos;re your growth partners from concept to scale.
          </DescriptionText>
          <Link href="/contact" passHref style={{ textDecoration: 'none' }}>
            <DiscoverButton sx={{ mt: "32px" }}>Discover</DiscoverButton>
          </Link>
        </TitleWrapper>

        <StatusWrapper>
          {statusData.map((item, index) => (
            <StatusCard
              key={index}
              sx={{
                // Background Image Logic
                ...(index === 0 || index === 2) && {
                  backgroundImage: "url('https://res.cloudinary.com/dlhe4iq8c/image/upload/v1770963764/ezgif-63db9d777461cb41_niae5n.gif')",
                  backgroundSize: "cover",
                  backgroundPosition: "center",
                },

                border: (theme) => `1px solid ${theme.palette.divider}`,
                margin: "-0.5px",

                // RADIUS LOGIC
                // Card 1 (Top Left)
                ...(index === 0 && {
                  borderTopLeftRadius: "12px",
                  borderTopRightRadius: { xs: "12px", sm: "0px" },
                  borderBottomLeftRadius: { xs: "0px", xl: "12px" },
                }),

                // Card 2 (Top Right in 2-col mode)
                ...(index === 1 && {
                  borderTopRightRadius: { xs: "0px", sm: "12px", xl: "0px" },
                }),

                // Card 3 (Bottom Left in 2-col mode)
                ...(index === 2 && {
                  borderBottomLeftRadius: { xs: "0px", sm: "12px", xl: "0px" },
                }),

                // Card 4 (Bottom Right)
                ...(index === 3 && {
                  borderBottomRightRadius: "12px",
                  borderTopRightRadius: { xs: "0px", xl: "12px" },
                  borderBottomLeftRadius: { xs: "12px", sm: "0px" },
                }),
              }}
            >
              <NumberText
                ref={(el: HTMLDivElement | null) => {
                  numberRefs.current[index] = el;
                }}
              >
                {item.prefix || ""}0{item.suffix || ""}
              </NumberText>

              <DescriptionText sx={{ color: "text.primary" }} variant="h5">
                {item.title}
              </DescriptionText>
            </StatusCard>
          ))}
        </StatusWrapper>
      </PageContainer>
    </TrackContainer>
  );
};

export default TrackRecord;